### PR TITLE
Fix compiler warnings

### LINKED ISSUE #150: Incorrect header path during compilation
https://github.com/Snowflake-Labs/pg_lake/blob/39230f95d2a1e5903fae2693d7da8da351368d0a/pg_lake_table/src/planner/query_pushdown.c#L73

Error during `make install ` on WSL Debian 12 with default installation of postgresql-18 from apt repo.

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fvisibility=hidden -Werror=implicit-function-declaration -I/usr/include/postgresql -Iinclude -I../pg_extension_base/include -I../pg_lake_engine/include -I../pg_lake_iceberg/include -I. -I./ -I/usr/include/postgresql/18/server -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE  -I/usr/include/libxml2     -c -o src/planner/query_pushdown.o src/planner/query_pushdown.c
> src/planner/query_pushdown.c:73:10: fatal error: server/rewrite/rewriteManip.h: No such file or directory
>    73 | #include "server/rewrite/rewriteManip.h"

Should be

>    73 | #include "rewrite/rewriteManip.h"

### PR DESCRIPTION
**Pull request by sfc-gh-mslot**
When compiling on Linux some warnings show up, also fixes #150

### CODE REVIEW

File: pg_lake_iceberg/src/rest_catalog/rest_catalog.c [hunk 1]
```diff
@@ -882,7 +882,7 @@ GetAddSnapshotCatalogRequest(IcebergSnapshot * newSnapshot, Oid relationId)
 	appendStringInfo(body, ",\"schema-id\":%d", newSnapshot->schema_id);
 	appendStringInfoString(body, "}}, ");	/* end add-snapshot */
 
-	appendStringInfo(body, "{\"action\":\"set-snapshot-ref\", \"type\":\"branch\", \"ref-name\":\"main\", \"snapshot-id\":%lld}", newSnapshot->snapshot_id);
+	appendStringInfo(body, "{\"action\":\"set-snapshot-ref\", \"type\":\"branch\", \"ref-name\":\"main\", \"snapshot-id\":" INT64_FORMAT "}", newSnapshot->snapshot_id);
```
Comment (sfc-gh-okalaci) [inline pg_lake_iceberg/src/rest_catalog/rest_catalog.c:885]: pff, my compiler doesn't like this:
```
Makefile:44: warning: overriding commands for target `check'
/Users/okalaci/pg-install/pg17/lib/postgresql/pgxs/src/makefiles/pgxs.mk:449: warning: ignoring old commands for target `check'
src/rest_catalog/rest_catalog.c:885:140: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
  885 |         appendStringInfo(body, "{\"action\":\"set-snapshot-ref\", \"type\":\"branch\", \"ref-name\":\"main\", \"snapshot-id\":" INT64_FORMAT "}", newSnapshot->snapshot_id);
      |                                                                                                                                 ~~~~~~~~~~~~      ^~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

File: pg_lake_engine/src/data_file/data_file_stats.c [hunk 2]
```diff
@@ -284,7 +284,7 @@ ExtractMinMaxForColumn(Datum map, const char *colName, List **names, List **mins
  * UnescapeDoubleQuotes unescapes any doubled quotes.
  * e.g. "ab\"\"cd\"\"ee" becomes "ab\"cd\"ee"
  */
-static const char *
+static char *
```
Comment (sfc-gh-okalaci) [inline pg_lake_engine/src/data_file/data_file_stats.c:287]: We should perhaps cast the return statement to `(char *)` as well?
```
src/data_file/data_file_stats.c:321:9: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  321 |         return s;
      |                ^
1 warning generated.
```

File: pg_lake_iceberg/src/rest_catalog/rest_catalog.c (hunk 1 above)
Comment (sfc-gh-okalaci) [inline pg_lake_iceberg/src/rest_catalog/rest_catalog.c:885]: I think `PRId64` works fine for MacOS any Linux, we have seem to use that throughout the code.

Comment (sfc-gh-mslot) [reply pg_lake_iceberg/src/rest_catalog/rest_catalog.c:885]: INT64_FORMAT is the convention in postgres code, but it's defined as PRId64

Comment (sfc-gh-okalaci) [reply pg_lake_iceberg/src/rest_catalog/rest_catalog.c:885]: Then, I should figure our the mystery why `INT64_FORMAT ` gives a warning but not  `PRId64 ` on my machine

Comment (sfc-gh-mslot) [reply pg_lake_iceberg/src/rest_catalog/rest_catalog.c:885]: It happens when inttypes.h is included after postgres.h (c.h), since it redefines it.
