### PR TITLE
Make write-through caching robust to file system errors

### LINKED ISSUE #123: Write-through caching is not working well with small cache sizes
In the code, we try to write-through 1GB without checking if there is enough size, you immediately start to see errors like the following when ingesting large amounts of data: 
```
 insert into public.events_iceberg select * from public.events_iceberg;select pg_size_pretty(lake_iceberg.table_size('public.events_iceberg'));
ERROR:  IO Error: Failed to create directory "/var/lib/duckdb/files/s3/6nmhen5cohitmhxoxoiyrspsmetujrxo/mxrx2fdbdfhn7ggc5uaevx4nee/postgres/public/events_iceberg/17538/data/0eb66c97-9b3f-4aa9-b587-0bd5d9baec14/": No space left on device
```

The above error is `Failed to create directory` from [here](https://github.com/Snowflake-Labs/pg_lake/blob/40fab1b2a9288764453e4a472a9b7042b41d692b/duckdb_pglake/src/fs/caching_file_system.cpp#L155-L161), even before we start writing, while creating a directory.

In case `Write` fails, we get a similar error:
```
psql:/tmp/f.sql:1: ERROR:  IO Error: Could not write file "/var/lib/duckdb/files/s3/6nmhen5cohitmhxoxoiyrspsmetujrxo/mxrx2fdbdfhn7ggc5uaevx4nee/postgres/public/events_iceberg/17538/metadata/pgl-cache.d6b544f0-b111-4386-b021-188f2d20e64d-m1.avro.pgl-stage": No space left on device
```

I think we should be more careful before deciding to use the write-through caching.

### PR DESCRIPTION
**Pull request by sfc-gh-okalaci**
Before this commit, we assumed that cache file creation or writing to the cache file never errors out. Well, that's definitely not true. Especially with small cache sizes, it can be pretty common to have file system errors, when the disk is full.

With this commit, if opening the cache file or writing to the cache file fails, we skip write-through caching. We also make sure to clean up anything that have been written as part of write-through caching.

Note that we refer this concept as `cacheOnWrite` in the code, we should perhaps change that on a follow-up PR to keep things simpler.

Closes #123

### CODE REVIEW

File: duckdb_pglake/src/include/pg_lake/fs/caching_file_system.hpp [hunk 1]
```diff
@@ -183,17 +183,39 @@ class DuckdbPGLakeCachingFileSystem : public FileSystem {
 		if (pg_lakeHandle.context->interrupted)
 			throw InterruptException();
 
+		bool cleanupCacheOnWriteFileIfNeeded = false;
```
Comment (sfc-gh-mslot) [inline duckdb_pglake/src/include/pg_lake/fs/caching_file_system.hpp]: super minor, maybe remove the IfNeeded. If this is true, then cleanup is needed.
